---
abstract: 'Conjugation of English verbs'
author:
  - 'Russ Graham <RWG@cpan.org>'
build_requires:
  Lingua::EN::Contraction: 0
  Memoize: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-Conjugate
provides:
  Lingua::EN::Conjugate:
    file: lib/Lingua/EN/Conjugate.pm
    version: 0.311
resources:
  license: http://dev.perl.org/licenses/
version: 0.311
