---
name: Lingua-EN-Conjugate
version: 0.303
author:
  - 'Russ Graham <RWG@cpan.org>'
abstract: Conjugation of English verbs
license: perl
build_requires:
  Lingua::EN::Conjugate: 0
  Test::More: 0
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Lingua::EN::Conjugate:
    file: lib/Lingua/EN/Conjugate.pm
    version: 0.303
resources:
  license: http://dev.perl.org/licenses/
